esphome:
  name: lights-ceiling
  includes:
    - blelights.h  
    #- blecodes.h # -> With each change of this file it needs to be included and then "removed" from the YAML. There must be a better way.
  libraries:
    - nkolban/ESP32 BLE Arduino@^1.0.1

esp32:
  board: esp32dev
  framework:
    type: arduino


# Custom light
light:
- platform: custom
  lambda: |-
    auto light_lab = new BLELights("LABROM");
    App.register_component(light_lab);
    return {light_lab};
  lights:
    - name: "Lab Light"
      id: light_lab
      default_transition_length: 0s
- platform: custom
  lambda: |-
    auto light_liv = new BLELights("LIVROOM");
    App.register_component(light_liv);
    return {light_liv};
  lights:
    - name: "Living Room Light"
      id: light_liv
      default_transition_length: 0s
- platform: custom
  lambda: |-
    auto light_bed = new BLELights("BEDROOM");
    App.register_component(light_bed);
    return {light_bed};
  lights:
    - name: "Bedroom Light"
      id: light_bed
      default_transition_length: 0s




# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: "REPLACE"

ota:
  password: "REPLACE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lights-Ceiling Fallback Hotspot"
    password: "REPLACE"

captive_portal:
    